<?php

return [
    [
        'title' => 'Products',
        'href' => '/products',
        'sub' => [
            [
                'title' => 'Brands',
                'href' => 'products',
                'src' => 'https://cdnm.sanmar.com/imglib/mresjpg/2014/f17/L455_jetblack_model_front_072014.jpg',
                'sub' => [
                    ['title' => 'A4', 'href' => 'products/brands/a4'],
                    ['title' => 'Allmade', 'href' => 'products/brands/allmade'],
                    ['title' => 'American Apparel', 'href' => 'products/brands/american-apparel'],
                    ['title' => 'BELLA+CANVAS', 'href' => 'products/brands/bella-canvas'],
                    ['title' => 'Brooks Brothers', 'href' => 'products/brands/brooks-brothers'],
                    ['title' => 'Bulwark', 'href' => 'products/brands/bulwark'],
                    ['title' => 'Carhartt', 'href' => 'products/brands/carhartt'],
                    ['title' => 'Champion', 'href' => 'products/brands/champion'],
                    ['title' => 'Comfort Colors', 'href' => 'products/brands/comfort-colors'],
                    ['title' => 'CornerStone', 'href' => 'products/brands/corner-stone'],
                    ['title' => 'Cotopaxi', 'href' => 'products/brands/cotopaxi'],
                    ['title' => 'District', 'href' => 'products/brands/district'],
                    ['title' => 'Eddie Bauer', 'href' => 'products/brands/eddie-bauer'],
                    ['title' => 'Gildan', 'href' => 'products/brands/gildan'],
                    ['title' => 'Hanes', 'href' => 'products/brands/hanes'],
                    ['title' => 'Jerzees', 'href' => 'products/brands/jerzees'],
                    ['title' => 'Mercer+Mettle', 'href' => 'products/brands/mercer-mettle'],
                    ['title' => 'New Era', 'href' => 'products/brands/new-era'],
                    ['title' => 'Next Level Apparel', 'href' => 'products/brands/next-level-apparel'],
                    ['title' => 'Nike', 'href' => 'products/brands/nike'],
                    ['title' => 'OGIO', 'href' => 'products/brands/ogio'],
                    ['title' => 'Outdoor Research', 'href' => 'products/brands/outdoor-research'],
                    ['title' => 'Port & Company', 'href' => 'products/brands/port-and-company'],
                    ['title' => 'Port Authority', 'href' => 'products/brands/port-authority'],
                    ['title' => 'Rabbit Skins', 'href' => 'products/brands/rabbit-skins'],
                    ['title' => 'Red Kap', 'href' => 'products/brands/red-kap'],
                    ['title' => 'Russell Outdoors', 'href' => 'products/brands/russell-outdoors'],
                    ['title' => 'Spacecraft', 'href' => 'products/brands/spacecraft'],
                    ['title' => 'Sport-Tek', 'href' => 'products/brands/sport-tek'],
                    ['title' => 'Stanley/Stella', 'href' => 'products/brands/stanley-stella'],
                    ['title' => 'tentree', 'href' => 'products/brands/tentree'],
                    ['title' => 'The North Face', 'href' => 'products/brands/the-north-face'],
                    ['title' => 'Tommy Bahama', 'href' => 'products/brands/tommy-bahama'],
                    ['title' => 'TravisMathew', 'href' => 'products/brands/travis-mathew'],
                    ['title' => 'Volunteer Knitwear', 'href' => 'products/brands/volunteer-knitwear'],
                    ['title' => 'Wink', 'href' => 'products/brands/wink']

                ],
            ],
            [
                'title' => 'T-Shirts',
                'href' => 'products/category/t-shirts',
                'src' => 'https://cdnm.sanmar.com/imglib/mresjpg/2017/f4/29M_oxford_model_front_032017.jpg',
                'special' => [
                    ['title' => 'New', 'href' => 'products/category/t-shirts/new'],
                    ['title' => 'Sale', 'href' => 'products/category/t-shirts/sale'],
                    ['title' => 'Discontinued', 'href' => 'products/category/t-shirts/discontinued'],
                ],
                'sub' => [
                    ['title' => '100% Cotton', 'href' => 'products/category/t-shirts/100-cotton'],
                    ['title' => '6-6.1 100% Cotton', 'href' => 'products/category/t-shirts/6-6-1'],
                    ['title' => '5-5.6 100% Cotton', 'href' => 'products/category/t-shirts/5-5-6'],
                    ['title' => '5-5.6 100% Cotton', 'href' => 'products/category/t-shirts/5-5-6'],
                    ['title' => 'Tri-Blend', 'href' => 'products/category/t-shirts/tri-blend'],
                    ['title' => '50/50 Blend', 'href' => 'products/category/t-shirts/50-50-blend'],
                    ['title' => 'Performance', 'href' => 'products/category/t-shirts/performance'],
                    ['title' => 'Tanks', 'href' => 'products/category/t-shirts/tanks'],
                    ['title' => "Women's", 'href' => 'products/category/t-shirts/womens'],
                    ['title' => 'Youth', 'href' => 'products/category/t-shirts/youth'],
                    ['title' => 'Ringspun', 'href' => 'products/category/t-shirts/ringspun'],
                    ['title' => 'Long Sleeve', 'href' => 'products/category/t-shirts/long-sleeve'],
                    ['title' => 'Specialty', 'href' => 'products/category/t-shirts/specialty'],
                    ['title' => 'Workwear', 'href' => 'products/category/t-shirts/workwear'],
                    ['title' => 'Tall', 'href' => 'products/category/t-shirts/tall'],
                    ['title' => 'Essentials', 'href' => 'products/category/t-shirts/essentials'],
                ]
            ],
            [
                'title' => 'Polos/Knits',
                'href' => 'products/category/polos-knits',
                'src' => 'https://cdnm.sanmar.com/imglib/mresjpg/2014/f13/K500P_ultramarineblue_model_front_072014.jpg',
                'special' => [
                    ['title' => 'New', 'href' => 'products/category/polos-knits/new'],
                    ['title' => 'Sale', 'href' => 'products/category/polos-knits/sale'],
                    ['title' => 'Discontinued', 'href' => 'products/category/polos-knits/discontinued'],
                ],
                'sub' => [
                    ['title' => "Performance", 'href' => 'products/category/polos-knits/performance'],
                    ['title' => "Easy Care", 'href' => 'products/category/polos-knits/easy-care'],
                    ['title' => "Silk Touch", 'href' => 'products/category/polos-knits/silk-touch'],
                    ['title' => "Cotton", 'href' => 'products/category/polos-knits/cotton'],
                    ['title' => "Workwear", 'href' => 'products/category/polos-knits/workwear'],
                    ['title' => "Sweaters", 'href' => 'products/category/polos-knits/sweaters'],
                    ['title' => "Mock/Turtlenecks", 'href' => 'products/category/polos-knits/mock-turtlenecks'],
                    ['title' => "Women's", 'href' => 'products/category/polos-knits/womens'],
                    ['title' => "Youth", 'href' => 'products/category/polos-knits/youth'],
                    ['title' => "Tall", 'href' => 'products/category/polos-knits/tall'],
                    ['title' => "Essentials", 'href' => 'products/category/polos-knits/essentials'],
                ]
            ],
            [
                'title' => 'Sweatshirts/Fleece',
                'href' => 'products/category/sweatshirts-fleece',
                'src' => 'https://cdnm.sanmar.com/imglib/mresjpg/2019/f15/PC78H_sangria_model_front_092019.jpg',
                'special' => [
                    ['title' => 'New', 'href' => 'products/category/sweatshirts-fleece/new'],
                    ['title' => 'Sale', 'href' => 'products/category/sweatshirts-fleece/sale'],
                    ['title' => 'Discontinued', 'href' => 'products/category/sweatshirts-fleece/discontinued'],
                ],
                'sub' => [
                    ['title' => 'Crewnecks', 'href' => 'products/category/sweatshirts-fleece/crewnecks'],
                    ['title' => 'Hoodie', 'href' => 'products/category/sweatshirts-fleece/hoodie'],
                    ['title' => 'Performance', 'href' => 'products/category/sweatshirts-fleece/performance'],
                    ['title' => 'Sweatpants', 'href' => 'products/category/sweatshirts-fleece/sweatpants'],
                    ['title' => '1/2 & 1/4 Zip', 'href' => 'products/category/sweatshirts-fleece/half-and-quarter-zip'],
                    ['title' => 'Full Zip', 'href' => 'products/category/sweatshirts-fleece/full-zip'],
                    ['title' => 'Fleece', 'href' => 'products/category/sweatshirts-fleece/fleece'],
                    ['title' => 'Heavyweight', 'href' => 'products/category/sweatshirts-fleece/heavyweight'],
                    ['title' => "Women's", 'href' => 'products/category/sweatshirts-fleece/womens'],
                    ['title' => "Youth", 'href' => 'products/category/sweatshirts-fleece/youth'],
                    ['title' => "Tall", 'href' => 'products/category/sweatshirts-fleece/tall'],
                    ['title' => "Essentials", 'href' => 'products/category/sweatshirts-fleece/essentials'],
                ]
            ],
            [
                'title' => 'Caps',
                'href' => 'products/category/caps',
                'src' => 'https://cdnm.sanmar.com/imglib/mresjpg/333114_VarsityRoyal_FlatFront_2009.jpg',
                'special' => [
                    ['title' => 'New', 'href' => 'products/category/caps/new'],
                    ['title' => 'Sale', 'href' => 'products/category/caps/sale'],
                    ['title' => 'Discontinued', 'href' => 'products/category/caps/discontinued'],
                ],
                'sub' => [
                    ['title' => 'Stretch Fit', 'href' => 'products/category/caps/stretch-fit'],
                    ['title' => 'Performance/Team', 'href' => 'products/category/caps/performance-team'],
                    ['title' => 'Flexfit', 'href' => 'products/category/caps/flexfit'],
                    ['title' => 'Mesh Back', 'href' => 'products/category/caps/mesh-back'],
                    ['title' => 'Structured', 'href' => 'products/category/caps/structured'],
                    ['title' => 'Unstructured', 'href' => 'products/category/caps/unstructured'],
                    ['title' => 'Pigment/Garment Dyed', 'href' => 'products/category/caps/pigment-garment-dyed'],
                    ['title' => 'Camouflage', 'href' => 'products/category/caps/camouflage'],
                    ['title' => 'Safety', 'href' => 'products/category/caps/safety'],
                    ['title' => 'Full Brim', 'href' => 'products/category/caps/full-brim'],
                    ['title' => 'Visors', 'href' => 'products/category/caps/visors'],
                    ['title' => 'Fleece/Beanies', 'href' => 'products/category/caps/fleece-beanies'],
                    ['title' => 'Twill', 'href' => 'products/category/caps/twill'],
                    ['title' => "Youth", 'href' => 'products/category/polos-knits/youth'],
                    ['title' => "Essentials", 'href' => 'products/category/polos-knits/essentials'],
                ]
            ],
            [
                'title' => 'Activewear',
                'href' => 'products/category/activewear',
                'src' => '//cdnp.sanmar.com/medias/sys_master/images/h06/h4c/16690109939742/424Wx635H_46779_DpRdWht-0-LST441DpRdWhtModelFront/424Wx635H-46779-DpRdWht-0-LST441DpRdWhtModelFront.jpg',
                'special' => [
                    ['title' => 'New', 'href' => 'products/category/activewear/new'],
                    ['title' => 'Sale', 'href' => 'products/category/activewear/sale'],
                    ['title' => 'Discontinued', 'href' => 'products/category/activewear/discontinued'],
                ],
                'sub' => [
                    ['title' => 'Performance', 'href' => 'products/category/activewear/performance'],
                    ['title' => 'Jerseys', 'href' => 'products/category/activewear/jerseys'],
                    ['title' => 'Tanks', 'href' => 'products/category/activewear/tanks'],
                    ['title' => 'Athletic/Warm-Ups', 'href' => 'products/category/activewear/athletic-warm-ups'],
                    ['title' => 'Baseball', 'href' => 'products/category/activewear/baseball'],
                    ['title' => 'Basketball', 'href' => 'products/category/activewear/basketball'],
                    ['title' => 'Pants & Shorts', 'href' => 'products/category/activewear/pants-and-shorts'],
                    ['title' => "Women's", 'href' => 'products/category/activewear/womens'],
                    ['title' => "Youth", 'href' => 'products/category/activewear/youth'],
                    ['title' => "Tall", 'href' => 'products/category/activewear/tall'],
                    ['title' => "Essentials", 'href' => 'products/category/activewear/essentials'],
                ]
            ],
            [
                'title' => 'Outerwear',
                'href' => 'products/category/outerwear',
                'src' => 'https://cdnm.sanmar.com/imglib/mresjpg/2016/f19/J777_navy_model_front_102016.jpg',
                'special' => [
                    ['title' => 'New', 'href' => 'products/category/outerwear/new'],
                    ['title' => 'Sale', 'href' => 'products/category/outerwear/sale'],
                    ['title' => 'Discontinued', 'href' => 'products/category/outerwear/discontinued'],
                ],
                'sub' => [
                    ['title' => 'Soft Shells', 'href' => 'products/category/outerwear/soft-shells'],
                    ['title' => 'Polyester Fleece', 'href' => 'products/category/outerwear/polyester-fleece'],
                    ['title' => 'Rainwear', 'href' => 'products/category/outerwear/rainwear'],
                    ['title' => '3-in-1', 'href' => 'products/category/outerwear/3-in-1'],
                    ['title' => 'Athletic/Warm-ups', 'href' => 'products/category/outerwear/athletic/warm-ups'],
                    ['title' => 'Vests', 'href' => 'products/category/outerwear/vests'],
                    ['title' => 'Corporate Jackets', 'href' => 'products/category/outerwear/corporate-jackets'],
                    ['title' => 'Work Jackets', 'href' => 'products/category/outerwear/work-jackets'],
                    ['title' => 'Golf Outerwear', 'href' => 'products/category/outerwear/golf-outerwear'],
                    ['title' => 'Insulated Jackets', 'href' => 'products/category/outerwear/insulated-jackets'],
                    ['title' => "Women's", 'href' => 'products/category/outerwear/womens'],
                    ['title' => "Youth", 'href' => 'products/category/outerwear/youth'],
                    ['title' => "Tall", 'href' => 'products/category/outerwear/tall'],
                    ['title' => "Essentials", 'href' => 'products/category/outerwear/essentials'],
                ]
            ],
            [
                'title' => 'Woven/Dress Shirts',
                'href' => 'products/category/woven-dress-shirts',
                'src' => 'https://cdnm.sanmar.com/imglib/mresjpg/2016/f17/S654_greenaqua_model_front_102016.jpg',
                'special' => [
                    ['title' => 'New', 'href' => 'products/category/woven-dress-shirts/new'],
                    ['title' => 'Sale', 'href' => 'products/category/woven-dress-shirts/sale'],
                    ['title' => 'Discontinued', 'href' => 'products/category/woven-dress-shirts/discontinued'],
                ],
                'sub' => [
                    ['title' => 'Easy Care', 'href' => 'products/category/woven-dress-shirts/easy-care'],
                    ['title' => 'Oxfords', 'href' => 'products/category/woven-dress-shirts/oxfords'],
                    ['title' => 'Denim', 'href' => 'products/category/woven-dress-shirts/denim'],
                    ['title' => 'Cotton', 'href' => 'products/category/woven-dress-shirts/cotton'],
                    ['title' => 'Fishing', 'href' => 'products/category/woven-dress-shirts/fishing'],
                    ['title' => 'Camp Shirts', 'href' => 'products/category/woven-dress-shirts/camp-shirts'],
                    ['title' => 'Cotton/Poly Blend', 'href' => 'products/category/woven-dress-shirts/cotton-poly-blend'],
                    ['title' => '100% Cotton', 'href' => 'products/category/woven-dress-shirts/100-cotton'],
                    ['title' => 'Premium Woven', 'href' => 'products/category/woven-dress-shirts/premium-woven'],

                    ['title' => "Women's", 'href' => 'products/category/woven-dress-shirts/womens'],
                    ['title' => "Tall", 'href' => 'products/category/woven-dress-shirts/tall'],
                    ['title' => "Essentials", 'href' => 'products/category/woven-dress-shirts/essentials'],
                ]
            ],
            [
                'title' => 'Bottoms',
                'href' => 'products/category/bottoms',
                'src' => 'https://cdnm.sanmar.com/imglib/mresjpg/LPST880_Black_Model_Front_121010.jpg',
                'special' => [
                    ['title' => 'New', 'href' => 'products/category/bottoms/new'],
                    ['title' => 'Sale', 'href' => 'products/category/bottoms/sale'],
                    ['title' => 'Discontinued', 'href' => 'products/category/bottoms/discontinued'],
                ],
                'sub' => [
                    ['title' => 'Sweatpants', 'href' => 'products/category/bottoms/sweatpants'],
                    ['title' => 'Joggers', 'href' => 'products/category/bottoms/joggers'],
                    ['title' => 'Shorts', 'href' => 'products/category/bottoms/shorts'],
                    ['title' => 'Workwear', 'href' => 'products/category/bottoms/workwear'],
                    ['title' => 'Scrub Pants', 'href' => 'products/category/bottoms/scrub-pants'],
                    ['title' => "Women's", 'href' => 'products/category/bottoms/womens'],
                    ['title' => "Youth", 'href' => 'products/category/bottoms/youth'],

                ]
            ],
            [
                'title' => 'Workwear',
                'href' => 'products/category/workwear',
                'src' => '//cdnp.sanmar.com/medias/sys_master/images/h95/h25/26574300545054/424Wx635H_8006_DarkNavy-0-CS419DarkNavyModelFront3/424Wx635H-8006-DarkNavy-0-CS419DarkNavyModelFront3.jpg',
                'special' => [
                    ['title' => 'New', 'href' => 'products/category/workwear/new'],
                    ['title' => 'Sale', 'href' => 'products/category/workwear/sale'],
                    ['title' => 'Discontinued', 'href' => 'products/category/workwear/discontinued'],
                ],
                'sub' => [
                    ['title' => 'Industrial Work Shirts', 'href' => 'products/category/workwear/industrial-work-shirts'],
                    ['title' => 'Stain/Soil Resistant', 'href' => 'products/category/workwear/stain/soil-resistant'],
                    [
                        'title' => 'Industrial Work Pants/Shorts',
                        'href' => 'products/category/workwear/industrial-work-pants-shorts'
                    ],
                    ['title' => 'Work  Jackets', 'href' => 'products/category/workwear/work-jackets'],
                    ['title' => 'Safety', 'href' => 'products/category/workwear/safety'],
                    ['title' => 'Aprons', 'href' => 'products/category/workwear/aprons'],
                    ['title' => 'Medical/Scrubs', 'href' => 'products/category/workwear/medical-scrubs'],
                    ['title' => "Tall", 'href' => 'products/category/workwear/tall'],
                ]
            ],
            [
                'title' => 'Bags',
                'href' => 'products/category/bags',
                'src' => 'https://cdnm.sanmar.com/imglib/mresjpg/2011/f7/411047_Black_GA12.jpg',
                'special' => [
                    ['title' => 'New', 'href' => 'products/category/bags/new'],
                    ['title' => 'Sale', 'href' => 'products/category/bags/sale'],
                    ['title' => 'Discontinued', 'href' => 'products/category/bags/discontinued'],
                ],
                'sub' => [
                    ['title' => 'Briefcases/Messengers', 'href' => 'products/category/bags/briefcases-messengers'],
                    ['title' => 'Backpacks', 'href' => 'products/category/bags/backpacks'],
                    ['title' => 'Duffels', 'href' => 'products/category/bags/duffels'],
                    ['title' => 'Travel Bags', 'href' => 'products/category/bags/travel-bags'],
                    ['title' => 'Golf Bags', 'href' => 'products/category/bags/golf-bags'],
                    ['title' => 'Coolers & Lunch Bags', 'href' => 'products/category/bags/coolers-and-lunch-bags'],
                    ['title' => 'Cinch Packs', 'href' => 'products/category/bags/cinch-packs'],
                    ['title' => 'Totes', 'href' => 'products/category/bags/totes'],
                    ['title' => 'Grocery Totes', 'href' => 'products/category/bags/grocery-totes'],
                    ['title' => 'Specialty Bags', 'href' => 'products/category/bags/specialty-bags'],
                    ['title' => 'Rolling Bags', 'href' => 'products/category/bags/rolling-bags'],
                    ['title' => "Essentials", 'href' => 'products/category/bags/essentials'],
                ]
            ],
            [
                'title' => 'Accessories',
                'href' => 'products/category/accessories',
                'src' => '//cdnp.sanmar.com/medias/sys_master/images/had/h7e/26568764719134/424Wx635H_6251_Black-0-A706BlackModelFront2/424Wx635H-6251-Black-0-A706BlackModelFront2.jpg',
                'special' => [
                    ['title' => 'New', 'href' => 'products/category/accessories/new'],
                    ['title' => 'Sale', 'href' => 'products/category/accessories/sale'],
                    ['title' => 'Discontinued', 'href' => 'products/category/accessories/discontinued'],
                ],
                'sub' => [
                    ['title' => 'Blankets', 'href' => 'products/category/accessories/blankets'],
                    ['title' => 'Robes/Towels', 'href' => 'products/category/accessories/robes-towels'],
                    ['title' => 'Golf Towels', 'href' => 'products/category/accessories/golf-towels'],
                    ['title' => 'Aprons', 'href' => 'products/category/accessories/aprons'],
                    ['title' => 'Scarves/Gloves', 'href' => 'products/category/accessories/scarves-gloves'],
                    ['title' => 'Other', 'href' => 'products/category/accessories/other'],
                    ['title' => 'Essential', 'href' => 'products/category/accessories/essential'],
                ]
            ],
            [
                'title' => 'Personal Protection',
                'href' => 'products/category/personal-protection',
                'src' => '//cdnp.sanmar.com/medias/sys_master/images/hb1/hed/26664827650078/424Wx635H_5726_SftyOrg-0-CS401LSSftyOrgModelFront3/424Wx635H-5726-SftyOrg-0-CS401LSSftyOrgModelFront3.jpg',
                'special' => [
                    ['title' => 'New', 'href' => 'products/category/personal-protection/new'],
                    ['title' => 'Sale', 'href' => 'products/category/personal-protection/sale'],
                    ['title' => 'Discontinued', 'href' => 'products/category/personal-protection/discontinued'],
                ],
                'sub' => [
                    ['title' => 'Face Coverings', 'href' => 'products/category/personal-protection/face-coverings'],
                    ['title' => 'Medical/Scrubs', 'href' => 'products/category/personal-protection/medical-scrubs'],
                    ['title' => 'Safety', 'href' => 'products/category/personal-protection/safety'],
                ]
            ],
            [
                'title' => "Women's",
                'href' => 'products/category/womens',
                'src' => 'https://cdnp.sanmar.com/medias/sys_master/images/h92/h34/17156006510622/1200W_6297_Black-0-FS07BlackModelFront3/1200W-6297-Black-0-FS07BlackModelFront3.jpg',
                'special' => [
                    ['title' => 'New', 'href' => 'products/category/womens/new'],
                    ['title' => 'Sale', 'href' => 'products/category/womens/sale'],
                    ['title' => 'Discontinued', 'href' => 'products/category/womens/discontinued'],
                ],
                'sub' => [
                    ['title' => 'T-Shirts', 'href' => 'products/category/womens/t-shirts'],
                    ['title' => 'Polos/Knits', 'href' => 'products/category/womens/polos/knits'],
                    ['title' => 'Sweatshirts/Fleece', 'href' => 'products/category/womens/sweatshirts-fleece'],
                    ['title' => 'Woven Shirts', 'href' => 'products/category/womens/woven-shirts'],
                    ['title' => 'Caps', 'href' => 'products/category/womens/caps'],
                    ['title' => 'Outerwear', 'href' => 'products/category/womens/outerwear'],
                    ['title' => 'Activewear', 'href' => 'products/category/womens/activewear'],
                    ['title' => 'bottoms', 'href' => 'products/category/womens/bottoms'],
                ]
            ],
            [
                'title' => 'Youth',
                'href' => 'products/category/youth',
                'src' => 'https://cdnm.sanmar.com/imglib/mresjpg/2015/f9/5400B_royal_model_front_042015.jpg',
                'special' => [
                    ['title' => 'New', 'href' => 'products/category/youth/new'],
                    ['title' => 'Sale', 'href' => 'products/category/youth/sale'],
                    ['title' => 'Discontinued', 'href' => 'products/category/youth/discontinued'],
                ],
                'sub' => [
                    ['title' => 'T-Shirts', 'href' => 'products/category/youth/t-shirts'],
                    ['title' => 'Polos/Knits', 'href' => 'products/category/youth/polos/knits'],
                    ['title' => 'Sweatshirts/Fleece', 'href' => 'products/category/youth/sweatshirts-fleece'],
                    ['title' => 'Caps', 'href' => 'products/category/youth/caps'],
                    ['title' => 'Outerwear', 'href' => 'products/category/youth/outerwear'],
                    ['title' => 'Activewear', 'href' => 'products/category/youth/activewear'],
                    ['title' => 'bottoms', 'href' => 'products/category/youth/bottoms'],
                    ['title' => 'Infant & Toddler', 'href' => 'products/category/youth/infant-and-toddler'],
                ]
            ],
        ]
    ],
    [
        'title' => 'Reversible Apparel',
        'href' => 'reversible-apparel',
    ],
    [
        'title' => 'School Specials',
        'href' => 'school-specials',
    ],
    [
        'title' => 'Our Company',
        'href' => 'our-company',
    ],
    [
        'title' => 'Contact Us',
        'href' => 'contact-us',
    ]
];
