<?php

return [
    [
        'title' => 'Products',
        'href' => '/products',
        'src' => 'https://ink-and-thread.com/storage/176/032819_Bella.jpg',
        'sub' => [
            [
                'title' => 'Brands',
                'href' => '/products/brands',
                'src' => 'https://cdnm.sanmar.com/imglib/mresjpg/2014/f17/L455_jetblack_model_front_072014.jpg',
                'sub' => [
                    ['title' => 'A4', 'href' => 'products/brands/a4', 'src' => 'a_4_banner'],
                    ['title' => 'Allmade', 'href' => 'products/brands/allmade', 'src' => 'allmade_banner'],
                    ['title' => 'American Apparel', 'href' => 'products/brands/american-apparel', 'src' => 'american_apparel_banner'],
                    ['title' => 'BELLA+CANVAS', 'href' => 'products/brands/bella-canvas', 'src' => 'bella_canvas_banner'],
                    ['title' => 'Brooks Brothers', 'href' => 'products/brands/brooks-brothers', 'src' => 'brooks_brothers_banner'],
                    ['title' => 'Bulwark', 'href' => 'products/brands/bulwark', 'src' => 'bulwark_banner'],
                    ['title' => 'Carhartt', 'href' => 'products/brands/carhartt', 'src' => 'carhartt_banner'],
                    ['title' => 'Champion', 'href' => 'products/brands/champion', 'src' => 'champion_banner'],
                    ['title' => 'Comfort Colors', 'href' => 'products/brands/comfort-colors', 'src' => 'comfort_colors_banner'],
                    ['title' => 'CornerStone', 'href' => 'products/brands/cornerstone', 'src' => 'cornerstone_banner'],
                    ['title' => 'Cotopaxi', 'href' => 'products/brands/cotopaxi', 'src' => 'cotopaxi_banner'],
                    ['title' => 'District', 'href' => 'products/brands/district', 'src' => 'district_banner'],
                    ['title' => 'Eddie Bauer', 'href' => 'products/brands/eddie-bauer', 'src' => 'eddie_bauer_banner'],
                    ['title' => 'Gildan', 'href' => 'products/brands/gildan', 'src' => 'gildan_banner'],
                    ['title' => 'Hanes', 'href' => 'products/brands/hanes', 'src' => 'hanes_banner'],
                    ['title' => 'Jerzees', 'href' => 'products/brands/jerzees', 'src' => 'jerzees_banner'],
                    ['title' => 'Mercer+Mettle', 'href' => 'products/brands/mercer-mettle', 'src' => 'mercer_mettle_banner'],
                    ['title' => 'New Era', 'href' => 'products/brands/new-era', 'src' => 'new_era_banner'],
                    ['title' => 'Next Level Apparel', 'href' => 'products/brands/next-level-apparel', 'src' => 'next_level_apparel_banner'],
                    ['title' => 'Nike', 'href' => 'products/brands/nike', 'src' => 'nike_banner'],
                    ['title' => 'OGIO', 'href' => 'products/brands/ogio', 'src' => 'ogio_banner'],
                    ['title' => 'Outdoor Research', 'href' => 'products/brands/outdoor-research', 'src' => 'outdoor_research_banner'],
                    ['title' => 'Port & Company', 'href' => 'products/brands/port-and-company', 'src' => 'port_company_banner'],
                    ['title' => 'Port Authority', 'href' => 'products/brands/port-authority', 'src' => 'port_authority_banner'],
                    ['title' => 'Rabbit Skins', 'href' => 'products/brands/rabbit-skins', 'src' => 'rabbit_skins_banner'],
                    ['title' => 'Red Kap', 'href' => 'products/brands/red-kap', 'src' => 'red_kap_banner'],
                    ['title' => 'Russell Outdoors', 'href' => 'products/brands/russell-outdoors', 'src' => 'russell_outdoors_banner'],
                    ['title' => 'Spacecraft', 'href' => 'products/brands/spacecraft', 'src' => 'spacecraft_banner'],
                    ['title' => 'Sport-Tek', 'href' => 'products/brands/sport-tek', 'src' => 'sport_banner_tek'],
                    ['title' => 'Stanley/Stella', 'href' => 'products/brands/stanley-stella', 'src' => 'stanley_stella_banner'],
                    ['title' => 'tentree', 'href' => 'products/brands/tentree', 'src' => 'tentree_banner'],
                    ['title' => 'The North Face', 'href' => 'products/brands/the-north-face', 'src' => 'the_north_face_banner'],
                    ['title' => 'Tommy Bahama', 'href' => 'products/brands/tommy-bahama', 'src' => 'tommy_bahama_banner'],
                    ['title' => 'TravisMathew', 'href' => 'products/brands/travis-mathew', 'src' => 'travis_mathew_banner'],
                    ['title' => 'Volunteer Knitwear', 'href' => 'products/brands/volunteer-knitwear', 'src' => 'volunteer_knitwear_banner'],
                    ['title' => 'Wink', 'href' => 'products/brands/wink', 'src' => 'wink_banner'],

                ],
            ],
            [
                'title' => 'T-Shirts',
                'href' => 'products/t-shirts',
                'src' => 'https://cdnm.sanmar.com/imglib/mresjpg/2017/f4/29M_oxford_model_front_032017.jpg',
                'special' => [
                    ['title' => 'New', 'href' => 'products/t-shirts/new'],
                    ['title' => 'Sale', 'href' => 'products/t-shirts/sale'],
                    ['title' => 'Discontinued', 'href' => 'products/t-shirts/discontinued'],
                ],
                'sub' => [
                    ['title' => '100% Cotton', 'href' => 'products/t-shirts/100-cotton'],
                    ['title' => '100% Polyester', 'href' => 'products/t-shirts/100-polyester'],
                    ['title' => 'blends', 'href' => 'products/t-shirts/blends'],
                    ['title' => 'Cotton Poly', 'href' => 'products/t-shirts/cotton-poly'],
                    ['title' => 'Jersey', 'href' => 'products/t-shirts/jersey'],
                    ['title' => 'Tri-Blend', 'href' => 'products/t-shirts/tri-blend'],
                    ['title' => '50/50 Blend', 'href' => 'products/t-shirts/50-50-blend'],
                    ['title' => 'Performance', 'href' => 'products/t-shirts/performance'],
                    ['title' => 'Tanks', 'href' => 'products/t-shirts/tanks'],
                    ['title' => "Women's", 'href' => 'products/t-shirts/womens'],
                    ['title' => 'Youth', 'href' => 'products/t-shirts/youth'],
                    ['title' => 'Ringspun', 'href' => 'products/t-shirts/ringspun'],
                    ['title' => 'Long Sleeve', 'href' => 'products/t-shirts/long-sleeve'],
                    ['title' => 'Specialty', 'href' => 'products/t-shirts/specialty'],
                    ['title' => 'Workwear', 'href' => 'products/t-shirts/workwear'],
                    ['title' => 'Tall', 'href' => 'products/t-shirts/tall'],
                    ['title' => 'Essentials', 'href' => 'products/t-shirts/essentials'],
                ]
            ],
            [
                'title' => 'Polos/Knits',
                'href' => 'products/polos-knits',
                'src' => 'https://cdnm.sanmar.com/imglib/mresjpg/2014/f13/K500P_ultramarineblue_model_front_072014.jpg',
                'special' => [
                    ['title' => 'New', 'href' => 'products/polos-knits/new'],
                    ['title' => 'Sale', 'href' => 'products/polos-knits/sale'],
                    ['title' => 'Discontinued', 'href' => 'products/polos-knits/discontinued'],
                ],
                'sub' => [
                    ['title' => "Performance", 'href' => 'products/polos-knits/performance'],
                    ['title' => "Easy Care", 'href' => 'products/polos-knits/easy-care'],
                    ['title' => "Silk Touch", 'href' => 'products/polos-knits/silk-touch'],
                    ['title' => "Cotton", 'href' => 'products/polos-knits/cotton'],
                    ['title' => "Workwear", 'href' => 'products/polos-knits/workwear'],
                    ['title' => "Sweaters", 'href' => 'products/polos-knits/sweaters'],
                    ['title' => "Mock/Turtlenecks", 'href' => 'products/polos-knits/mock-turtlenecks'],
                    ['title' => "Women's", 'href' => 'products/polos-knits/womens'],
                    ['title' => "Youth", 'href' => 'products/polos-knits/youth'],
                    ['title' => "Tall", 'href' => 'products/polos-knits/tall'],
                    ['title' => "Essentials", 'href' => 'products/polos-knits/essentials'],
                ]
            ],
            [
                'title' => 'Sweatshirts/Fleece',
                'href' => 'products/sweatshirts-fleece',
                'src' => 'https://cdnm.sanmar.com/imglib/mresjpg/2019/f15/PC78H_sangria_model_front_092019.jpg',
                'special' => [
                    ['title' => 'New', 'href' => 'products/sweatshirts-fleece/new'],
                    ['title' => 'Sale', 'href' => 'products/sweatshirts-fleece/sale'],
                    ['title' => 'Discontinued', 'href' => 'products/sweatshirts-fleece/discontinued'],
                ],
                'sub' => [
                    ['title' => 'Crewnecks', 'href' => 'products/sweatshirts-fleece/crewnecks'],
                    ['title' => 'Hoodie', 'href' => 'products/sweatshirts-fleece/hoodie'],
                    ['title' => 'Performance', 'href' => 'products/sweatshirts-fleece/performance'],
                    ['title' => 'Sweatpants', 'href' => 'products/sweatshirts-fleece/sweatpants'],
                    ['title' => '1/2 & 1/4 Zip', 'href' => 'products/sweatshirts-fleece/half-and-quarter-zip'],
                    ['title' => 'Full Zip', 'href' => 'products/sweatshirts-fleece/full-zip'],
                    ['title' => 'Fleece', 'href' => 'products/sweatshirts-fleece/fleece'],
                    ['title' => 'Heavyweight', 'href' => 'products/sweatshirts-fleece/heavyweight'],
                    ['title' => "Women's", 'href' => 'products/sweatshirts-fleece/womens'],
                    ['title' => "Youth", 'href' => 'products/sweatshirts-fleece/youth'],
                    ['title' => "Tall", 'href' => 'products/sweatshirts-fleece/tall'],
                    ['title' => "Essentials", 'href' => 'products/sweatshirts-fleece/essentials'],
                ]
            ],
            [
                'title' => 'Caps',
                'href' => 'products/caps',
                'src' => 'https://cdnm.sanmar.com/imglib/mresjpg/333114_VarsityRoyal_FlatFront_2009.jpg',
                'special' => [
                    ['title' => 'New', 'href' => 'products/caps/new'],
                    ['title' => 'Sale', 'href' => 'products/caps/sale'],
                    ['title' => 'Discontinued', 'href' => 'products/caps/discontinued'],
                ],
                'sub' => [
                    ['title' => 'Stretch Fit', 'href' => 'products/caps/stretch-fit'],
                    ['title' => 'Performance/Team', 'href' => 'products/caps/performance-team'],
                    ['title' => 'Flexfit', 'href' => 'products/caps/flexfit'],
                    ['title' => 'Mesh Back', 'href' => 'products/caps/mesh-back'],
                    ['title' => 'Structured', 'href' => 'products/caps/structured'],
                    ['title' => 'Unstructured', 'href' => 'products/caps/unstructured'],
                    ['title' => 'Pigment/Garment Dyed', 'href' => 'products/caps/pigment-garment-dyed'],
                    ['title' => 'Camouflage', 'href' => 'products/caps/camouflage'],
                    ['title' => 'Safety', 'href' => 'products/caps/safety'],
                    ['title' => 'Full Brim', 'href' => 'products/caps/full-brim'],
                    ['title' => 'Visors', 'href' => 'products/caps/visors'],
                    ['title' => 'Fleece/Beanies', 'href' => 'products/caps/fleece-beanies'],
                    ['title' => 'Twill', 'href' => 'products/caps/twill'],
                    ['title' => "Youth", 'href' => 'products/polos-knits/youth'],
                    ['title' => "Essentials", 'href' => 'products/polos-knits/essentials'],
                ]
            ],
            [
                'title' => 'Activewear',
                'href' => 'products/activewear',
                'src' => '//cdnp.sanmar.com/medias/sys_master/images/h06/h4c/16690109939742/424Wx635H_46779_DpRdWht-0-LST441DpRdWhtModelFront/424Wx635H-46779-DpRdWht-0-LST441DpRdWhtModelFront.jpg',
                'special' => [
                    ['title' => 'New', 'href' => 'products/activewear/new'],
                    ['title' => 'Sale', 'href' => 'products/activewear/sale'],
                    ['title' => 'Discontinued', 'href' => 'products/activewear/discontinued'],
                ],
                'sub' => [
                    ['title' => 'Performance', 'href' => 'products/activewear/performance'],
                    ['title' => 'Jerseys', 'href' => 'products/activewear/jerseys'],
                    ['title' => 'Tanks', 'href' => 'products/activewear/tanks'],
                    ['title' => 'Athletic/Warm-Ups', 'href' => 'products/activewear/athletic-warm-ups'],
                    ['title' => 'Baseball', 'href' => 'products/activewear/baseball'],
                    ['title' => 'Basketball', 'href' => 'products/activewear/basketball'],
                    ['title' => 'Pants & Shorts', 'href' => 'products/activewear/pants-and-shorts'],
                    ['title' => "Women's", 'href' => 'products/activewear/womens'],
                    ['title' => "Youth", 'href' => 'products/activewear/youth'],
                    ['title' => "Tall", 'href' => 'products/activewear/tall'],
                    ['title' => "Essentials", 'href' => 'products/activewear/essentials'],
                ]
            ],
            [
                'title' => 'Outerwear',
                'href' => 'products/outerwear',
                'src' => 'https://cdnm.sanmar.com/imglib/mresjpg/2016/f19/J777_navy_model_front_102016.jpg',
                'special' => [
                    ['title' => 'New', 'href' => 'products/outerwear/new'],
                    ['title' => 'Sale', 'href' => 'products/outerwear/sale'],
                    ['title' => 'Discontinued', 'href' => 'products/outerwear/discontinued'],
                ],
                'sub' => [
                    ['title' => 'Soft Shells', 'href' => 'products/outerwear/soft-shells'],
                    ['title' => 'Polyester Fleece', 'href' => 'products/outerwear/polyester-fleece'],
                    ['title' => 'Rainwear', 'href' => 'products/outerwear/rainwear'],
                    ['title' => '3-in-1', 'href' => 'products/outerwear/3-in-1'],
                    ['title' => 'Athletic/Warm-ups', 'href' => 'products/outerwear/athletic/warm-ups'],
                    ['title' => 'Vests', 'href' => 'products/outerwear/vests'],
                    ['title' => 'Corporate Jackets', 'href' => 'products/outerwear/corporate-jackets'],
                    ['title' => 'Work Jackets', 'href' => 'products/outerwear/work-jackets'],
                    ['title' => 'Golf Outerwear', 'href' => 'products/outerwear/golf-outerwear'],
                    ['title' => 'Insulated Jackets', 'href' => 'products/outerwear/insulated-jackets'],
                    ['title' => "Women's", 'href' => 'products/outerwear/womens'],
                    ['title' => "Youth", 'href' => 'products/outerwear/youth'],
                    ['title' => "Tall", 'href' => 'products/outerwear/tall'],
                    ['title' => "Essentials", 'href' => 'products/outerwear/essentials'],
                ]
            ],
            [
                'title' => 'Woven/Dress Shirts',
                'href' => 'products/woven-dress-shirts',
                'src' => 'https://cdnm.sanmar.com/imglib/mresjpg/2016/f17/S654_greenaqua_model_front_102016.jpg',
                'special' => [
                    ['title' => 'New', 'href' => 'products/woven-dress-shirts/new'],
                    ['title' => 'Sale', 'href' => 'products/woven-dress-shirts/sale'],
                    ['title' => 'Discontinued', 'href' => 'products/woven-dress-shirts/discontinued'],
                ],
                'sub' => [
                    ['title' => 'Easy Care', 'href' => 'products/woven-dress-shirts/easy-care'],
                    ['title' => 'Oxfords', 'href' => 'products/woven-dress-shirts/oxfords'],
                    ['title' => 'Denim', 'href' => 'products/woven-dress-shirts/denim'],
                    ['title' => 'Cotton', 'href' => 'products/woven-dress-shirts/cotton'],
                    ['title' => 'Fishing', 'href' => 'products/woven-dress-shirts/fishing'],
                    ['title' => 'Camp Shirts', 'href' => 'products/woven-dress-shirts/camp-shirts'],
                    ['title' => 'Cotton/Poly Blend', 'href' => 'products/woven-dress-shirts/cotton-poly-blend'],
                    ['title' => '100% Cotton', 'href' => 'products/woven-dress-shirts/100-cotton'],
                    ['title' => 'Premium Woven', 'href' => 'products/woven-dress-shirts/premium-woven'],

                    ['title' => "Women's", 'href' => 'products/woven-dress-shirts/womens'],
                    ['title' => "Tall", 'href' => 'products/woven-dress-shirts/tall'],
                    ['title' => "Essentials", 'href' => 'products/woven-dress-shirts/essentials'],
                ]
            ],
            [
                'title' => 'Bottoms',
                'href' => 'products/bottoms',
                'src' => 'https://cdnm.sanmar.com/imglib/mresjpg/LPST880_Black_Model_Front_121010.jpg',
                'special' => [
                    ['title' => 'New', 'href' => 'products/bottoms/new'],
                    ['title' => 'Sale', 'href' => 'products/bottoms/sale'],
                    ['title' => 'Discontinued', 'href' => 'products/bottoms/discontinued'],
                ],
                'sub' => [
                    ['title' => 'Sweatpants', 'href' => 'products/bottoms/sweatpants'],
                    ['title' => 'Joggers', 'href' => 'products/bottoms/joggers'],
                    ['title' => 'Shorts', 'href' => 'products/bottoms/shorts'],
                    ['title' => 'Workwear', 'href' => 'products/bottoms/workwear'],
                    ['title' => 'Scrub Pants', 'href' => 'products/bottoms/scrub-pants'],
                    ['title' => "Women's", 'href' => 'products/bottoms/womens'],
                    ['title' => "Youth", 'href' => 'products/bottoms/youth'],

                ]
            ],
            [
                'title' => 'Workwear',
                'href' => 'products/workwear',
                'src' => '//cdnp.sanmar.com/medias/sys_master/images/h95/h25/26574300545054/424Wx635H_8006_DarkNavy-0-CS419DarkNavyModelFront3/424Wx635H-8006-DarkNavy-0-CS419DarkNavyModelFront3.jpg',
                'special' => [
                    ['title' => 'New', 'href' => 'products/workwear/new'],
                    ['title' => 'Sale', 'href' => 'products/workwear/sale'],
                    ['title' => 'Discontinued', 'href' => 'products/workwear/discontinued'],
                ],
                'sub' => [
                    ['title' => 'Industrial Work Shirts', 'href' => 'products/workwear/industrial-work-shirts'],
                    ['title' => 'Stain/Soil Resistant', 'href' => 'products/workwear/stain/soil-resistant'],
                    ['title' => 'Industrial Work Pants/Shorts', 'href' => 'products/workwear/industrial-work-pants-shorts'],
                    ['title' => 'Work  Jackets', 'href' => 'products/workwear/work-jackets'],
                    ['title' => 'Safety', 'href' => 'products/workwear/safety'],
                    ['title' => 'Aprons', 'href' => 'products/workwear/aprons'],
                    ['title' => 'Medical/Scrubs', 'href' => 'products/workwear/medical-scrubs'],
                    ['title' => "Tall", 'href' => 'products/workwear/tall'],
                ]
            ],
            [
                'title' => 'Bags',
                'href' => 'products/bags',
                'src' => 'https://cdnm.sanmar.com/imglib/mresjpg/2011/f7/411047_Black_GA12.jpg',
                'special' => [
                    ['title' => 'New', 'href' => 'products/bags/new'],
                    ['title' => 'Sale', 'href' => 'products/bags/sale'],
                    ['title' => 'Discontinued', 'href' => 'products/bags/discontinued'],
                ],
                'sub' => [
                    ['title' => 'Briefcases/Messengers', 'href' => 'products/bags/briefcases-messengers'],
                    ['title' => 'Backpacks', 'href' => 'products/bags/backpacks'],
                    ['title' => 'Duffels', 'href' => 'products/bags/duffels'],
                    ['title' => 'Travel Bags', 'href' => 'products/bags/travel-bags'],
                    ['title' => 'Golf Bags', 'href' => 'products/bags/golf-bags'],
                    ['title' => 'Coolers & Lunch Bags', 'href' => 'products/bags/coolers-and-lunch-bags'],
                    ['title' => 'Cinch Packs', 'href' => 'products/bags/cinch-packs'],
                    ['title' => 'Totes', 'href' => 'products/bags/totes'],
                    ['title' => 'Grocery Totes', 'href' => 'products/bags/grocery-totes'],
                    ['title' => 'Specialty Bags', 'href' => 'products/bags/specialty-bags'],
                    ['title' => 'Rolling Bags', 'href' => 'products/bags/rolling-bags'],
                    ['title' => "Essentials", 'href' => 'products/bags/essentials'],
                ]
            ],
            [
                'title' => 'Accessories',
                'href' => 'products/accessories',
                'src' => '//cdnp.sanmar.com/medias/sys_master/images/had/h7e/26568764719134/424Wx635H_6251_Black-0-A706BlackModelFront2/424Wx635H-6251-Black-0-A706BlackModelFront2.jpg',
                'special' => [
                    ['title' => 'New', 'href' => 'products/accessories/new'],
                    ['title' => 'Sale', 'href' => 'products/accessories/sale'],
                    ['title' => 'Discontinued', 'href' => 'products/accessories/discontinued'],
                ],
                'sub' => [
                    ['title' => 'Blankets', 'href' => 'products/accessories/blankets'],
                    ['title' => 'Robes/Towels', 'href' => 'products/accessories/robes-towels'],
                    ['title' => 'Golf Towels', 'href' => 'products/accessories/golf-towels'],
                    ['title' => 'Aprons', 'href' => 'products/accessories/aprons'],
                    ['title' => 'Scarves/Gloves', 'href' => 'products/accessories/scarves-gloves'],
                    ['title' => 'Other', 'href' => 'products/accessories/other'],
                    ['title' => 'Essential', 'href' => 'products/accessories/essential'],
                ]
            ],
            [
                'title' => 'Personal Protection',
                'href' => 'products/personal-protection',
                'src' => '//cdnp.sanmar.com/medias/sys_master/images/hb1/hed/26664827650078/424Wx635H_5726_SftyOrg-0-CS401LSSftyOrgModelFront3/424Wx635H-5726-SftyOrg-0-CS401LSSftyOrgModelFront3.jpg',
                'special' => [
                    ['title' => 'New', 'href' => 'products/personal-protection/new'],
                    ['title' => 'Sale', 'href' => 'products/personal-protection/sale'],
                    ['title' => 'Discontinued', 'href' => 'products/personal-protection/discontinued'],
                ],
                'sub' => [
                    ['title' => 'Face Coverings', 'href' => 'products/personal-protection/face-coverings'],
                    ['title' => 'Medical/Scrubs', 'href' => 'products/personal-protection/medical-scrubs'],
                    ['title' => 'Safety', 'href' => 'products/personal-protection/safety'],
                ]
            ],
            [
                'title' => "Women's",
                'href' => 'products/womens',
                'src' => 'https://cdnp.sanmar.com/medias/sys_master/images/h92/h34/17156006510622/1200W_6297_Black-0-FS07BlackModelFront3/1200W-6297-Black-0-FS07BlackModelFront3.jpg',
                'special' => [
                    ['title' => 'New', 'href' => 'products/womens/new'],
                    ['title' => 'Sale', 'href' => 'products/womens/sale'],
                    ['title' => 'Discontinued', 'href' => 'products/womens/discontinued'],
                ],
                'sub' => [
                    ['title' => 'T-Shirts', 'href' => 'products/womens/t-shirts'],
                    ['title' => 'Polos/Knits', 'href' => 'products/womens/polos/knits'],
                    ['title' => 'Sweatshirts/Fleece', 'href' => 'products/womens/sweatshirts-fleece'],
                    ['title' => 'Woven Shirts', 'href' => 'products/womens/woven-shirts'],
                    ['title' => 'Caps', 'href' => 'products/womens/caps'],
                    ['title' => 'Outerwear', 'href' => 'products/womens/outerwear'],
                    ['title' => 'Activewear', 'href' => 'products/womens/activewear'],
                    ['title' => 'bottoms', 'href' => 'products/womens/bottoms'],
                ]
            ],
            [
                'title' => 'Youth',
                'href' => 'products/youth',
                'src' => 'https://cdnm.sanmar.com/imglib/mresjpg/2015/f9/5400B_royal_model_front_042015.jpg',
                'special' => [
                    ['title' => 'New', 'href' => 'products/youth/new'],
                    ['title' => 'Sale', 'href' => 'products/youth/sale'],
                    ['title' => 'Discontinued', 'href' => 'products/youth/discontinued'],
                ],
                'sub' => [
                    ['title' => 'T-Shirts', 'href' => 'products/youth/t-shirts'],
                    ['title' => 'Polos/Knits', 'href' => 'products/youth/polos/knits'],
                    ['title' => 'Sweatshirts/Fleece', 'href' => 'products/youth/sweatshirts-fleece'],
                    ['title' => 'Caps', 'href' => 'products/youth/caps'],
                    ['title' => 'Outerwear', 'href' => 'products/youth/outerwear'],
                    ['title' => 'Activewear', 'href' => 'products/youth/activewear'],
                    ['title' => 'Infant & Toddler', 'href' => 'products/youth/infant-and-toddler'],
                ]
            ],
        ]
    ],
    [
        'title' => 'Reversible Apparel',
        'href' => 'reversible-apparel',
        'description' => "Looking for a unique and comfortable sweatshirt that will have you turning heads. Our reversible sweatshirts allow you to have two looks in one.",

    ],
    [
        'title' => 'School Specials',
        'href' => 'school-specials',
        'description' => "Bring your school’s pride to life with custom graphics!  From screen printing to embroidery, heat press and DTG printing.  We offer endless options to showcase your school spirit. T-shirts, sweatshirts, hoodies, and more - designed just for you!",
    ],
    [
        'title' => 'Our Company',
        'href' => 'our-company',
        'description' => "You envision It. We create It.",
    ],
    [
        'title' => 'Contact Us',
        'href' => 'contact-us',
        'description' => "We're happy to answer questions and get you acquainted with Custom Ink and Thread.",
    ]
];
