<?php

namespace App\Support;


readonly class SubCategorySupport
{


    public static function lookupSubCategory(string $category): string
    {
        return collect([
            '100% Cotton' => '100% Cotton',
            '100% Polyester' => '100% Polyester',
            'Cotton Poly' => 'Cotton Poly',
            'Jersey' => 'Jersey',
            'Tri-Blend' => 'Tri-Blend',
            '50/50 Blend' => '50/50 Blend',
            'Tanks' => 'Tanks',
            "Women's" => "Women's",
            'Youth' => 'Youth',
            'Ringspun' => 'Ringspun',
            'Long Sleeve' => 'Long Sleeve',
            'Specialty' => 'Specialty',
            'Workwear' => 'Workwear',
            'Tall' => 'Tall',
            'Essentials' => 'Essentials',
            "Easy Care" => "Easy Care",
            "Silk Touch" => "Silk Touch",
            "Cotton" => "Cotton",
            "Sweaters" => "Sweaters",
            "Mock/Turtlenecks" => "Mock/Turtlenecks",
            'Crewneck' => 'Crewneck',
            'Hoodie' => 'Hoodie',
            'Sweatpants' => 'Sweatpants',
            '1/2 & 1/4 Zip' => '1/2 & 1/4 Zip',
            'Full Zip' => 'Full Zip',
            'Fleece' => 'Fleece',
            'Heavyweight' => 'Heavyweight',
            'Stretch Fit' => 'Stretch Fit',
            'Performance/Team' => 'Performance/Team',
            'Flexfit' => 'Flexfit',
            'Mesh Back' => 'Mesh Back',
            'Structured' => 'Structured',
            'Unstructured' => 'Unstructured',
            'Pigment/Garment Dyed' => 'Pigment/Garment Dyed',
            'Camouflage' => 'Camouflage',
            'Safety' => 'Safety',
            'Full Brim' => 'Full Brim',
            'Visors' => 'Visors',
            'Fleece/Beanies' => 'Fleece/Beanies',
            'Twill' => 'Twill',
            'Jerseys' => 'Jerseys',
            'Athletic/Warm-Ups' => 'Athletic/Warm-Ups',
            'Baseball' => 'Baseball',
            'Basketball' => 'Basketball',
            'Pants & Shorts' => 'Pants & Shorts',
            'Soft Shells' => 'Soft Shells',
            'Polyester Fleece' => 'Polyester Fleece',
            'Rainwear' => 'Rainwear',
            '3-in-1' => '3-in-1',
            'Athletic/Warm-ups' => 'Athletic/Warm-ups',
            'Vests' => 'Vests',
            'Corporate Jackets' => 'Corporate Jackets',
            'Work Jackets' => 'Work Jackets',
            'Golf Outerwear' => 'Golf Outerwear',
            'Insulated Jackets' => 'Insulated Jackets',
            'Oxfords' => 'Oxfords',
            'Denim' => 'Denim',
            'Fishing' => 'Fishing',
            'Camp Shirts' => 'Camp Shirts',
            'Cotton/Poly Blend' => 'Cotton/Poly Blend',
            'Premium Woven' => 'Premium Woven',
            'Joggers' => 'Joggers',
            'Shorts' => 'Shorts',
            'Scrub Pants' => 'Scrub Pants',
            'Industrial Work Shirts' => 'Industrial Work Shirts',
            'Stain/Soil Resistant' => 'Stain/Soil Resistant',
            'Industrial Work Pants/Shorts' => 'Industrial Work Pants/Shorts',
            'Aprons' => 'Aprons',
            'Medical/Scrubs' => 'Medical/Scrubs',
            'Briefcases/Messengers' => 'Briefcases/Messengers',
            'Backpacks' => 'Backpacks',
            'Duffels' => 'Duffels',
            'Travel Bags' => 'Travel Bags',
            'Golf Bags' => 'Golf Bags',
            'Coolers & Lunch Bags' => 'Coolers & Lunch Bags',
            'Cinch Packs' => 'Cinch Packs',
            'Totes' => 'Totes',
            'Grocery Totes' => 'Grocery Totes',
            'Specialty Bags' => 'Specialty Bags',
            'Rolling Bags' => 'Rolling Bags',
            'Blankets' => 'Blankets',
            'Robes/Towels' => 'Robes/Towels',
            'Golf Towels' => 'Golf Towels',
            'Scarves/Gloves' => 'Scarves/Gloves',
            'Other' => 'Other',
            'Essential' => 'Essential',
            'Face Coverings' => 'Face Coverings',
            'T-Shirts' => 'T-Shirts',
            'Polos/Knits' => 'Polos/Knits',
            'Sweatshirts/Fleece' => 'Sweatshirts/Fleece',
            'Woven Shirts' => 'Woven Shirts',
            'Infant & Toddler' => 'Infant & Toddler',
        ])->get($category, '100% Cotton');
    }

}
