<?php

namespace App\Support;


readonly class SubCategorySupport
{


    public static function lookupSubCategory(string $category): string
    {
        return collect([
            '100-cotton' => '100% Cotton',
            '6-6-1-100-Cotton' => '6-6.1 100% Cotton' ,
            '5-5-6-100-Cotton' => '5-5.6 100% Cotton',
            'performance'  => 'Performance',
            'cotton-poly-blend' => 'Cotton/Poly Blend',
            'jerseys' => 'Jerseys',
            '50-50-blend' => '50/50 Blend',
            'tanks' => 'Tanks',
            "womens" => "Women's",
            'youth' => 'Youth',
            'ring-spun' => 'Ring Spun',
            'long-sleeve' => 'Long Sleeve',
            'specialty' => 'Specialty',
            'workwear' => 'Workwear',
            'tall' => 'Tall',
            'essentials' => 'Essentials',
            "easy-care" => "Easy Care",
            "silk-touch" => "Silk Touch",
            "cotton" => "Cotton",
            "sweaters" => "Sweaters",
            "mock-turtlenecks" => "Mock & Turtlenecks",
            'crewneck' => 'Crewneck',
            'hoodie' => 'Hoodie',
            'sweatpants' => 'Sweatpants',
            'half-and-quarter-zip' => '1/2 & 1/4 Zip',
            'full-zip' => 'Full Zip',
            'fleece' => 'Fleece',
            'heavyweight' => 'Heavyweight',
            'stretch-fit' => 'Stretch Fit',
            'performance-athletic' => 'Performance/ Athletic',
            'flexfit' => 'Flexfit',
            'mesh-back' => 'Mesh Back',
            'structured' => 'Structured',
            'unstructured' => 'Unstructured',
            'pigment-garment-dyed' => 'Pigment/Garment Dyed',
            'camouflage' => 'Camouflage',
            'safety' => 'Safety',
            'full-brim' => 'Full Brim',
            'visors' => 'Visors',
            'fleece-beanies' => 'Fleece/Beanies',
            'twill' => 'Twill',
            'baseball' => 'Baseball',
            'basketball' => 'Basketball',
            'pants-and-shorts' => 'Pants & Shorts',
            'soft-shells' => 'Soft Shells',
            'polyester-fleece' => 'Polyester Fleece',
            'rainwear' => 'Rainwear',
            '3-in-1' => '3-in-1',
            'athletic-warm-ups' => 'Athletic/Warm-Ups',
            'vests' => 'Vests',
            'corporate-jackets' => 'Corporate Jackets',
            'work-jackets' => 'Work Jackets',
            'golf-outerwear' => 'Golf Outerwear',
            'outerwear' => 'Outerwear',
            'activewear' => 'Activewear',
            'caps' => 'Caps',
            'insulated-jackets' => 'Insulated Jackets',
            'oxfords' => 'Oxfords',
            'denim' => 'Denim',
            'fishing' => 'Fishing',
            'camp-shirts' => 'Camp Shirts',
            'bottoms' => 'Bottoms',
            'premium-woven' => 'Premium Woven',
            'joggers' => 'Joggers',
            'shorts' => 'Shorts',
            'scrub-pants' => 'Scrub Pants',
            'industrial-work-shirts' => 'Industrial Work Shirts',
            'stain/soil-resistant' => 'Stain/Soil Resistant',
            'industrial-work-pants-shorts' => 'Industrial Work Pants/Shorts',
            'aprons' => 'Aprons',
            'medical-scrubs' => 'Medical/Scrubs',
            'briefcases-messengers' => 'Briefcases/ Messengers',
            'backpacks' => 'Backpacks',
            'duffels' => 'Duffels',
            'travel-bags' => 'Travel Bags',
            'golf-bags' => 'Golf Bags',
            'coolers-and-lunch-bags' => 'Coolers & Lunch Bags',
            'cinch-packs' => 'Cinch Packs',
            'totes' => 'Totes',
            'grocery-totes' => 'Grocery Totes',
            'specialty-bags' => 'Specialty Bags',
            'rolling-bags' => 'Rolling Bags',
            'blankets' => 'Blankets',
            'robes-towels' => 'Robes/Towels',
            'golf-towels' => 'Golf Towels',
            'scarves-gloves' => 'Scarves/Gloves',
            'other' => 'Other',
            'essential' => 'Essential',
            'face-coverings' => 'Face Coverings',
            't-shirts' => 'T-Shirts',
            'polos-knits' => 'Polos/Knits',
            'sweatshirts-fleece' => 'Sweatshirts/Fleece',
            'woven-shirts' => 'Woven Shirts',
            'infant-and-toddler' => 'Infant & Toddler',
        ])->get($category, '100% Cotton');
    }

}
